name: first-action

on:
  push:
    branches:
      - "main"

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello message
        run: echo "Hello from first job!"

      - name: multi command step
        run: |
          echo "Hello from MULTI"
          git -v

  second-job:
    runs-on: ubuntu-latest
    needs: [ first-job ]

    steps:
      - name: Print hello message
        run: echo "Hello from second job!"
